name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - uses: actions/cache@v4
        id: cache-npm
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: lint
        run: |
          npm run lint
          npm run clippy
      - name: format
        run: |
          npm run prettier:check
          npm run fmt

  contract-test:
    runs-on: ubuntu-latest
    needs: [setup, check]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install WebAssembly target
        run: rustup target add wasm32-unknown-unknown
      - name: Install IC SDK
        run: DFX_VERSION=0.14.1 sh -ci "$(curl -sSL https://internetcomputer.org/install.sh)"
      - name: unit test
        run: npm run test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
